# Edit to fit your needs


[proxy]
bind = "8080"
use_gzip = true

# Define routes
[[routes]]
prefix = "/httpbin"
target = "https://httpbin.org"

[[routes]]
prefix = "/golang"
target = "https://golang.org"

[[routes]]
prefix = "/github"
target = "https://github.com"
